/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.pachumon.hellogradle;

public class Library {
    public Boolean someLibraryMethod() {
        return true;
    }
}
